[build]
  base = ""
  publish = "site"
  command = ""
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*/index.html"
  to = "/:splat/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
